services:
  v-code:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: v-code
    restart: unless-stopped
    ports:
      - "1291:3000"
    env_file:
      - .env.local
    environment:
      - NODE_ENV=production
    networks:
      - v-code-network

networks:
  v-code-network:
    driver: bridge
